import { PrismaClient } from '@prisma/client';

export async function seedStates(prisma: PrismaClient) {
  const countries = await prisma.country.findMany({
    select: {
      id: true,
      name: true,
    },
  });

  const countryMap = new Map(
    countries.map((country) => [country.name, country.id]),
  );

  const allStatesByCountry: Record<string, string[]> = {
    Nigeria: [
      'Abia',
      'Adamawa',
      'Akwa Ibom',
      'Anambra',
      'Bauchi',
      'Bayelsa',
      'Benue',
      'Borno',
      'Cross River',
      'Delta',
      'Ebonyi',
      'Edo',
      'Ekiti',
      'Enugu',
      'Gombe',
      'Imo',
      'Jigawa',
      'Kaduna',
      'Kano',
      'Katsina',
      'Kebbi',
      'Kogi',
      'Kwara',
      'Lagos',
      'Nasarawa',
      'Niger',
      'Ogun',
      'Ondo',
      'Osun',
      'Oyo',
      'Plateau',
      'Rivers',
      'Sokoto',
      'Taraba',
      'Yobe',
      'Zamfara',
      'FCT',
    ],

    'United States': [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
      'District of Columbia',
    ],

    Netherlands: [
      'Drenthe',
      'Flevoland',
      'Friesland',
      'Gelderland',
      'Groningen',
      'Limburg',
      'North Brabant',
      'North Holland',
      'Overijssel',
      'South Holland',
      'Utrecht',
      'Zeeland',
    ],

    Belgium: [
      'Antwerp',
      'East Flanders',
      'Flemish Brabant',
      'Hainaut',
      'Liège',
      'Limburg',
      'Luxembourg',
      'Namur',
      'Walloon Brabant',
      'West Flanders',
      'Brussels',
    ],

    Switzerland: [
      'Zurich',
      'Bern',
      'Lucerne',
      'Uri',
      'Schwyz',
      'Obwalden',
      'Nidwalden',
      'Glarus',
      'Zug',
      'Fribourg',
      'Solothurn',
      'Basel-Stadt',
      'Basel-Landschaft',
      'Schaffhausen',
      'Appenzell Ausserrhoden',
      'Appenzell Innerrhoden',
      'St. Gallen',
      'Graubünden',
      'Aargau',
      'Thurgau',
      'Ticino',
      'Vaud',
      'Valais',
      'Neuchâtel',
      'Geneva',
      'Jura',
    ],

    Sweden: [
      'Stockholm',
      'Uppsala',
      'Södermanland',
      'Östergötland',
      'Jönköping',
      'Kronoberg',
      'Kalmar',
      'Gotland',
      'Blekinge',
      'Skåne',
      'Halland',
      'Västra Götaland',
      'Värmland',
      'Örebro',
      'Västmanland',
      'Dalarna',
      'Gävleborg',
      'Västernorrland',
      'Jämtland',
      'Västerbotten',
      'Norrbotten',
    ],

    Norway: [
      'Oslo',
      'Rogaland',
      'Møre og Romsdal',
      'Nordland',
      'Viken',
      'Innlandet',
      'Vestfold og Telemark',
      'Agder',
      'Vestland',
      'Trøndelag',
      'Troms',
      'Finnmark',
    ],

    Denmark: [
      'Capital Region',
      'Central Denmark',
      'North Denmark',
      'Region Zealand',
      'Region of Southern Denmark',
    ],

    Austria: [
      'Burgenland',
      'Carinthia',
      'Lower Austria',
      'Upper Austria',
      'Salzburg',
      'Styria',
      'Tyrol',
      'Vorarlberg',
      'Vienna',
    ],

    Poland: [
      'Lower Silesian',
      'Kuyavian-Pomeranian',
      'Lublin',
      'Lubusz',
      'Łódź',
      'Lesser Poland',
      'Masovian',
      'Opole',
      'Podkarpackie',
      'Podlaskie',
      'Pomeranian',
      'Silesian',
      'Świętokrzyskie',
      'Warmian-Masurian',
      'Greater Poland',
      'West Pomeranian',
    ],

    Indonesia: [
      'Aceh',
      'Bali',
      'Banten',
      'Jakarta',
      'West Java',
      'Central Java',
      'East Java',
      'Yogyakarta',
      'North Sumatra',
      'South Sumatra',
      'West Sumatra',
      'Riau',
      'Papua',
      'West Papua',
    ],

    Malaysia: [
      'Johor',
      'Kedah',
      'Kelantan',
      'Kuala Lumpur',
      'Malacca',
      'Negeri Sembilan',
      'Pahang',
      'Penang',
      'Perak',
      'Perlis',
      'Sabah',
      'Sarawak',
      'Selangor',
      'Terengganu',
    ],

    Singapore: ['Central', 'North East', 'North West', 'South East', 'South West'],

    Pakistan: [
      'Punjab',
      'Sindh',
      'Khyber Pakhtunkhwa',
      'Balochistan',
      'Islamabad Capital Territory',
      'Gilgit-Baltistan',
      'Azad Kashmir',
    ],

    Bangladesh: [
      'Dhaka',
      'Chattogram',
      'Khulna',
      'Rajshahi',
      'Barishal',
      'Sylhet',
      'Rangpur',
      'Mymensingh',
    ],

    'United Arab Emirates': [
      'Abu Dhabi',
      'Dubai',
      'Sharjah',
      'Ajman',
      'Umm Al Quwain',
      'Ras Al Khaimah',
      'Fujairah',
    ],

    'Saudi Arabia': [
      'Riyadh',
      'Makkah',
      'Madinah',
      'Eastern Province',
      'Asir',
      'Jazan',
      'Tabuk',
      'Najran',
      'Al Bahah',
      'Al Jawf',
      'Northern Borders',
      'Hail',
      'Qassim',
    ],

    Algeria: [
        'Adrar',
        'Aïn Defla',
        'Aïn Témouchent',
        'Algiers',
        'Annab',
        'Bachar',
        'Batna',
        'Béjaïa',
        'Beni Abbes',
        'Biskra',
        'Blida',
        'Bordj Badji Mokhtar',
        'Bordj Bou Arréridj',
        'Bouira',
        'Boumerdès',
        'Chlef',
        'Constantine',
        'Djanet',
        'Djelfa',
        'El Bayadh',
        'El M\'Ghair',
        'El Meniaa',
        'El Oued',
        'El Tarf',
        'Ghardaïa',
        'Guelma',
        'In Guezzam',
        'In Salah',
        'Jijel',
        'Khenchela',
        'Laghouat',
        'M\'Sila',
        'Mascara',
        'Medea',
        'Mila',
        'Mostaganem',
        'Mosteghanem',
        'Naama',
        'Oran',
        'Ouargla',
        'Ouled Djellal',
        'Oum El Bouaghi',
        'Relizane',
        'Saïda',
        'Sétif',
        'Sidi Bel Abbès',
        'Skikda',
        'Souk Ahras',
        'Tamanrasset',
        'Tébessa',
        'Tiaret',
        'Tindouf',
        'Tipaza',
        'Tissemsilt',
        'Tizi Ouzou',
        'Tlemcen',
        'Touggourt',
        'Timimoun',
    ],

    Tunisia: [
        'Ariana',
        'Béja',
        'Ben Arous',
        'Bizerte',
        'Gabès',
        'Gafsa',
        'Jendouba',
        'Kairouan',
        'Kasserine',
        'Kebili',
        'Kef',
        'Mahdia',
        'Manouba',
        'Medenine',
        'Monastir',
        'Nabeul',
        'Sfax',
        'Sidi Bouzid',
        'Siliana',
        'Sousse',
        'Tataouine',
        'Tozeur',
        'Tunis',
        'Zaghouan',
    ],


    Uganda: [
      'Central',
      'Eastern',
      'Northern',
      'Western'
    ],

    Tanzania: [
        'Arusha',
        'Dar es Salaam',
        'Dodoma',
        'Geita',
        'Iringa',
        'Kagera',
        'Katavi',
        'Kigoma',
        'Kilimanjaro',
        'Lindi',
        'Manyara',
        'Mara',
        'Mbeya',
        'Mjini Magharibi',
        'Morogoro',
        'Mtwara',
        'Mwanza',
        'Njombe',
        'Pemba North',
        'Pemba South',
        'Pwani',
        'Rukwa',
        'Ruvuma',
        'Shinyanga',
        'Simiyu',
        'Singida',
        'Songwe',
        'Tabora',
        'Tanga',
        'Unguja North',
        'Unguja South',
    ],

    Rwanda: [
      'Kigali',
      'Eastern Province',
      'Northern Province',
      'Southern Province',
      'Western Province'
    ],

    Ethiopia: [
      'Addis Ababa',
      'Afar',
      'Amhara',
      'Benishangul-Gumuz',
      'Dire Dawa',
      'Gambela',
      'Harari',
      'Oromia',
      'Sidama',
      'Somali',
      'South West Ethiopia',
      'Southern Nations',
      'Tigray'
    ],

    Finland: [
      'Central Finland',
      'Kymenlaakso',
      'Lapland',
      'North Karelia',
      'North Ostrobothnia',
      'Pirkanmaa',
      'South Karelia',
      'South Ostrobothnia',
      'Uusimaa'
    ],

    Portugal: [
      'Aveiro',
      'Braga',
      'Coimbra',
      'Faro',
      'Leiria',
      'Lisbon',
      'Madeira',
      'Porto',
      'Santarém',
      'Setúbal'
    ],

    'South Korea': [
      'Busan',
      'Daegu',
      'Daejeon',
      'Gangwon',
      'Gwangju',
      'Gyeonggi',
      'Incheon',
      'Jeju',
      'North Chungcheong',
      'North Gyeongsang',
      'Seoul',
      'South Chungcheong',
      'South Gyeongsang',
      'Ulsan'
    ],

    Thailand: [
        'Bangkok',
        'Chiang Mai',
        'Chiang Rai',
        'Chonburi',
        'Khon Kaen',
        'Nakhon Ratchasima',
        'Nonthaburi',
        'Pathum Thani',
        'Phuket',
        'Songkhla'
    ],

    Vietnam: [
        'An Giang',
        'Bac Giang',
        'Can Tho',
        'Da Nang',
        'Dong Nai',
        'Hai Phong',
        'Hanoi',
        'Ho Chi Minh City',
        'Khanh Hoa',
        'Nghe An'
    ],


    Philippines: [
        'Cagayan Valley',
        'Calabarzon',
        'Central Luzon',
        'Central Visayas',
        'Davao Region',
        'Ilocos Region',
        'Metro Manila',
        'Northern Mindanao',
        'Soccsksargen',
        'Western Visayas'
    ],

    Qatar: [
        'Al Daayen',
        'Al Khor',
        'Al Rayyan',
        'Al Wakrah',
        'Doha',
        'Madinat ash Shamal',
        'Umm Salal'
    ],

    Mexico: [
        'Aguascalientes',
        'Baja California',
        'Chiapas',
        'Chihuahua',
        'Guanajuato',
        'Jalisco',
        'Mexico City',
        'Nuevo León',
        'Puebla',
        'Yucatán'
    ],

    Argentina: [
        'Buenos Aires',
        'Catamarca',
        'Chaco',
        'Córdoba',
        'Entre Ríos',
        'Mendoza',
        'Neuquén',
        'Salta',
        'Santa Fe',
        'Tucumán'
    ],

    Chile: [
        'Antofagasta',
        'Araucanía',
        'Atacama',
        'Biobío',
        'Coquimbo',
        'Los Lagos',
        'Maule',
        'Santiago Metropolitan',
        'Tarapacá',
        'Valparaíso'
    ],

    Colombia: [
        'Antioquia',
        'Atlántico',
        'Bolívar',
        'Boyacá',
        'Cauca',
        'Cundinamarca',
        'Nariño',
        'Santander',
        'Valle del Cauca',
        'Bogotá'
    ],

    'New Zealand': [
        'Auckland',
        'Bay of Plenty',
        'Canterbury',
        'Gisborne',
        'Hawke’s Bay',
        'Manawatu-Whanganui',
        'Northland',
        'Otago',
        'Southland',
        'Taranaki',
        'Waikato',
        'Wellington'
    ],
  };

  let totalInserted = 0;

  for (const [countryName, states] of Object.entries(allStatesByCountry)) {
    const countryId = countryMap.get(countryName);

    if (!countryId) {
      console.warn(`Country not found: ${countryName}`);
      continue;
    }

    const stateData = states.map((name) => ({
      name,
      countryId,
    }));

    const result = await prisma.state.createMany({
      data: stateData,
      skipDuplicates: true,
    });

    totalInserted += result.count;
  }

  console.log(`✅ Inserted ${totalInserted} states`);
}