export enum KYC_COMPLETED {
  PERSONAL_INFORMATION = 'PERSONAL_INFORMATION',
  IDENTITY_INFORMATION = 'IDENTITY_INFORMATION',
  RESIDENTIAL_INFORMATION = 'RESIDENTIAL_INFORMATION',
  ALL_COMPLETED = 'ALL_COMPLETED',
  NOT_COMPLETED = 'NOT_COMPLETED',
}