export enum PROOF_OF_ADDRESS_TYPE {
  UTILITY_BILL = 'UTILITY_BILL',
  BANK_STATEMENT = 'BANK_STATEMENT',
  RENTAL_AGREEMENT = 'RENTAL_AGREEMENT',
  GOVERNMENT_LETTER = 'GOVERNMENT_LETTER',
  TAX_DOCUMENT = 'TAX_DOCUMENT',
  INSURANCE_DOCUMENT = 'INSURANCE_DOCUMENT',
  OTHER = 'OTHER',
}


