import { QuestionCategory, QuestionDifficulty, JobRole } from '@prisma/client';
export const SAFETY_QUESTIONS = [
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Seat belts should be:',
    options: [
      { optionText: 'Used by all occupants', isCorrect: true },
      { optionText: 'Optional', isCorrect: false },
      { optionText: 'Used only on highways', isCorrect: false },
      { optionText: 'Used only at night', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question:
      'You receive a personal phone call while driving. What should you do?',
    options: [
      {
        optionText: 'Stop safely or use approved hands-free systems',
        isCorrect: true,
      },
      { optionText: 'Answer immediately', isCorrect: false },
      { optionText: 'Hold the phone while driving', isCorrect: false },
      { optionText: 'Ignore traffic laws', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question:
      'A passenger offers extra money if you exceed the speed limit. What should you do?',
    options: [
      { optionText: 'Politely refuse and obey traffic laws', isCorrect: true },
      { optionText: 'Accept and speed', isCorrect: false },
      { optionText: 'Speed on empty roads', isCorrect: false },
      { optionText: 'Negotiate a larger payment', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'The primary responsibility of a professional driver is:',
    options: [
      { optionText: 'Safety', isCorrect: true },
      { optionText: 'Speed', isCorrect: false },
      { optionText: 'Profit', isCorrect: false },
      { optionText: 'Entertainment', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question:
      'While driving, a passenger asks you to check a message on their phone. What should you do?',
    options: [
      { optionText: 'Decline and focus on driving safely', isCorrect: true },
      { optionText: 'Read it quickly', isCorrect: false },
      { optionText: 'Take the phone while driving', isCorrect: false },
      { optionText: 'Look when traffic is light', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question:
      'You notice a warning light appear on the dashboard during a trip. What should you do?',
    options: [
      {
        optionText: 'Assess the warning and follow safety procedures',
        isCorrect: true,
      },
      { optionText: 'Ignore it', isCorrect: false },
      { optionText: 'Drive faster to finish quickly', isCorrect: false },
      { optionText: 'Switch off the warning light', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Fatigue while driving can:',
    options: [
      { optionText: 'Reduce reaction time and judgment', isCorrect: true },
      { optionText: 'Improve concentration', isCorrect: false },
      { optionText: 'Increase awareness', isCorrect: false },
      { optionText: 'Improve decision-making', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A passenger is not wearing a seat belt. What should you do?',
    options: [
      {
        optionText: 'Politely remind them about safety requirements',
        isCorrect: true,
      },
      { optionText: 'Ignore it', isCorrect: false },
      { optionText: 'Start driving immediately', isCorrect: false },
      { optionText: 'Argue aggressively', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'What is defensive driving?',
    options: [
      {
        optionText: 'Driving in a way that anticipates hazards',
        isCorrect: true,
      },
      { optionText: 'Driving aggressively', isCorrect: false },
      { optionText: 'Driving faster than traffic', isCorrect: false },
      { optionText: 'Avoiding mirrors', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question:
      'Weather conditions suddenly worsen during a trip. What should you do?',
    options: [
      { optionText: 'Adjust driving behavior for conditions', isCorrect: true },
      { optionText: 'Maintain normal speed', isCorrect: false },
      { optionText: 'Speed up to finish quickly', isCorrect: false },
      { optionText: 'Ignore visibility changes', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question:
      'You are running behind schedule and risk receiving a poor rating. What should you do?',
    options: [
      { optionText: 'Maintain safe driving practices', isCorrect: true },
      { optionText: 'Drive faster than normal', isCorrect: false },
      { optionText: 'Ignore traffic regulations', isCorrect: false },
      { optionText: 'Take unsafe shortcuts', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question:
      'A passenger insists you make an illegal U-turn to save time. What should you do?',
    options: [
      {
        optionText: 'Politely refuse and follow traffic laws',
        isCorrect: true,
      },
      { optionText: 'Comply to satisfy the passenger', isCorrect: false },
      { optionText: 'Do it if traffic is light', isCorrect: false },
      { optionText: 'Do it only once', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question:
      'You suspect another driver on the road is impaired. What is the safest action?',
    options: [
      { optionText: 'Maintain distance and avoid engagement', isCorrect: true },
      { optionText: 'Challenge the driver', isCorrect: false },
      { optionText: 'Race ahead', isCorrect: false },
      { optionText: 'Follow closely', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question:
      'An EV battery is draining unusually quickly during a trip. What should you prioritize?',
    options: [
      {
        optionText: 'Passenger safety and contingency planning',
        isCorrect: true,
      },
      { optionText: 'Hiding the issue', isCorrect: false },
      { optionText: 'Increasing speed', isCorrect: false },
      { optionText: 'Ignoring battery warnings', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question:
      'A minor collision occurs with no visible injuries. What should you do first?',
    options: [
      {
        optionText: 'Ensure safety and follow incident procedures',
        isCorrect: true,
      },
      { optionText: 'Leave immediately', isCorrect: false },
      { optionText: 'Argue about fault', isCorrect: false },
      { optionText: 'Ignore reporting requirements', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Safe following distance helps drivers:',
    options: [
      { optionText: 'React to unexpected hazards', isCorrect: true },
      { optionText: 'Reach destinations faster', isCorrect: false },
      { optionText: 'Reduce fuel use only', isCorrect: false },
      { optionText: 'Impress passengers', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Vehicle inspections before work are important because:',
    options: [
      {
        optionText: 'Potential issues can be identified early',
        isCorrect: true,
      },
      { optionText: 'They are only paperwork', isCorrect: false },
      { optionText: 'They are optional', isCorrect: false },
      { optionText: 'They delay operations', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'Which action demonstrates the strongest safety culture?',
    options: [
      {
        optionText: 'Reporting hazards even when inconvenient',
        isCorrect: true,
      },
      { optionText: 'Ignoring minor risks', isCorrect: false },
      { optionText: 'Avoiding documentation', isCorrect: false },
      { optionText: 'Waiting for someone else to act', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question:
      'If visibility becomes severely reduced during a trip, the best response is:',
    options: [
      { optionText: 'Slow down and adapt to conditions', isCorrect: true },
      { optionText: 'Maintain normal speed', isCorrect: false },
      { optionText: 'Speed up', isCorrect: false },
      { optionText: 'Ignore the situation', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.DRIVER,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question:
      'A passenger pressures you to break multiple safety rules because they are late. What should guide your decision?',
    options: [
      { optionText: 'Safety and legal compliance', isCorrect: true },
      { optionText: 'Passenger pressure', isCorrect: false },
      { optionText: 'Potential tips', isCorrect: false },
      { optionText: 'Ratings only', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'When speaking with a customer, your tone should always be:',
    options: [
      { optionText: 'Rude', isCorrect: false },
      { optionText: 'Dismissive', isCorrect: false },
      { optionText: 'Polite and professional', isCorrect: true },
      { optionText: 'Sarcastic', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Customer account information should be treated as:',
    options: [
      { optionText: 'Public knowledge', isCorrect: false },
      { optionText: 'Shareable with friends', isCorrect: false },
      { optionText: 'Unimportant', isCorrect: false },
      { optionText: 'Confidential', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'If you do not know the answer to a customer question, you should:',
    options: [
      { optionText: 'Hang up', isCorrect: false },
      { optionText: 'Find the correct information or escalate', isCorrect: true },
      { optionText: 'Guess an answer', isCorrect: false },
      { optionText: 'Make something up', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Active listening with a customer means:',
    options: [
      { optionText: 'Thinking about your next task', isCorrect: false },
      { optionText: 'Fully focusing on what they are saying', isCorrect: true },
      { optionText: 'Reading unrelated messages', isCorrect: false },
      { optionText: 'Interrupting often', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Response times to customer queries should be:',
    options: [
      { optionText: 'Ignored', isCorrect: false },
      { optionText: 'As fast as possible without sacrificing accuracy', isCorrect: true },
      { optionText: 'Random', isCorrect: false },
      { optionText: 'Delayed deliberately', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'When a customer is upset, the first step is to:',
    options: [
      { optionText: 'End the conversation', isCorrect: false },
      { optionText: 'Transfer without explanation', isCorrect: false },
      { optionText: 'Argue back', isCorrect: false },
      { optionText: 'Acknowledge their concern calmly', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Promises made to customers should be:',
    options: [
      { optionText: 'Within your actual authority and ability to deliver', isCorrect: true },
      { optionText: 'Exaggerated to please them', isCorrect: false },
      { optionText: 'Vague on purpose', isCorrect: false },
      { optionText: 'Anything that ends the call quickly', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A customer becomes verbally abusive during a call. What should you do?',
    options: [
      { optionText: 'Mute and ignore them', isCorrect: false },
      { optionText: 'Insult them back', isCorrect: false },
      { optionText: 'Stay calm, set boundaries, and follow escalation procedure', isCorrect: true },
      { optionText: 'Hang up immediately without notice', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A customer asks for a refund outside of policy. What should you do?',
    options: [
      { optionText: 'Approve it to avoid conflict', isCorrect: false },
      { optionText: 'Explain the policy and offer applicable alternatives', isCorrect: true },
      { optionText: 'Deny it without explanation', isCorrect: false },
      { optionText: 'Tell them to call back later', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You accidentally gave a customer incorrect information. What should you do?',
    options: [
      { optionText: 'Ignore it', isCorrect: false },
      { optionText: 'Correct the mistake and inform them promptly', isCorrect: true },
      { optionText: 'Blame the customer', isCorrect: false },
      { optionText: 'Hope they do not notice', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A customer shares sensitive personal data during a chat. You should:',
    options: [
      { optionText: 'Save it for personal use', isCorrect: false },
      { optionText: 'Forward it to coworkers casually', isCorrect: false },
      { optionText: 'Post it in a team chat', isCorrect: false },
      { optionText: 'Handle it according to data privacy policy', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Handling multiple customer chats at once requires:',
    options: [
      { optionText: 'Careful prioritization and accuracy', isCorrect: true },
      { optionText: 'Copy-pasting irrelevant replies', isCorrect: false },
      { optionText: 'Ignoring some chats', isCorrect: false },
      { optionText: 'Rushing through all of them', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A customer requests a discount you are not authorized to give. What should you do?',
    options: [
      { optionText: 'Make up a smaller discount', isCorrect: false },
      { optionText: 'Tell them it is impossible without checking', isCorrect: false },
      { optionText: 'Escalate to someone with proper authority', isCorrect: true },
      { optionText: 'Give it anyway', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Why is documenting customer interactions important?',
    options: [
      { optionText: 'It wastes time', isCorrect: false },
      { optionText: 'It creates accurate records for future reference', isCorrect: true },
      { optionText: 'It is optional', isCorrect: false },
      { optionText: 'It is only for management', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A customer threatens to leave a bad review unless given special treatment. What should you do?',
    options: [
      { optionText: 'Remain professional and follow standard procedure', isCorrect: true },
      { optionText: 'Threaten them back', isCorrect: false },
      { optionText: 'Comply regardless of policy', isCorrect: false },
      { optionText: 'Hang up immediately', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A customer demands access to another customer\'s account information. What should you do?',
    options: [
      { optionText: 'Provide partial information', isCorrect: false },
      { optionText: 'Provide it if they sound convincing', isCorrect: false },
      { optionText: 'Ask a coworker to share it', isCorrect: false },
      { optionText: 'Refuse and explain privacy policy applies', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You are under pressure to close tickets quickly, risking unresolved customer issues. What should guide your action?',
    options: [
      { optionText: 'Closing as many tickets as possible', isCorrect: false },
      { optionText: 'Ignoring unresolved cases', isCorrect: false },
      { optionText: 'Quality and accuracy over speed', isCorrect: true },
      { optionText: 'Marking issues resolved regardless', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A colleague asks you to falsify a customer satisfaction report. What should you do?',
    options: [
      { optionText: 'Ignore the request silently', isCorrect: false },
      { optionText: 'Falsify it partially', isCorrect: false },
      { optionText: 'Comply to help the colleague', isCorrect: false },
      { optionText: 'Refuse and report the request appropriately', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A system outage prevents you from resolving customer issues. What should you prioritize?',
    options: [
      { optionText: 'Blaming the customer for the inconvenience', isCorrect: false },
      { optionText: 'Transparent communication and managing expectations', isCorrect: true },
      { optionText: 'Disappearing until it is fixed', isCorrect: false },
      { optionText: 'Promising immediate resolution regardless', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A customer mentions they are in personal distress unrelated to your service. What should you do?',
    options: [
      { optionText: 'Ignore it and continue with the script', isCorrect: false },
      { optionText: 'Respond with empathy and redirect to appropriate resources if needed', isCorrect: true },
      { optionText: 'Give personal advice', isCorrect: false },
      { optionText: 'End the conversation', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You discover a recurring product defect from multiple complaints. What should you do?',
    options: [
      { optionText: 'Keep handling complaints individually without reporting', isCorrect: false },
      { optionText: 'Tell customers it is their fault', isCorrect: false },
      { optionText: 'Escalate the pattern to the relevant team', isCorrect: true },
      { optionText: 'Dismiss the complaints', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'Which action best demonstrates a strong customer-first culture?',
    options: [
      { optionText: 'Closing tickets without confirmation', isCorrect: false },
      { optionText: 'Avoiding difficult conversations', isCorrect: false },
      { optionText: 'Prioritizing speed over resolution', isCorrect: false },
      { optionText: 'Following up to ensure an issue was truly resolved', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A manager pressures you to mislead customers about a delay. What should you do?',
    options: [
      { optionText: 'Quit immediately', isCorrect: false },
      { optionText: 'Mislead the customers as instructed', isCorrect: false },
      { optionText: 'Raise the ethical concern through proper channels', isCorrect: true },
      { optionText: 'Mislead only some customers', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A customer\'s issue requires input from another department that is slow to respond. What should you do?',
    options: [
      { optionText: 'Proactively follow up and keep the customer informed', isCorrect: true },
      { optionText: 'Close the ticket to remove it from your queue', isCorrect: false },
      { optionText: 'Tell the customer nothing can be done', isCorrect: false },
      { optionText: 'Stop responding to the customer', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.CUSTOMER_SUPPORT,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'When transferring a customer to another department, you should:',
    options: [
      { optionText: 'Brief the customer and the next agent clearly', isCorrect: true },
      { optionText: 'Hang up instead', isCorrect: false },
      { optionText: 'Leave them on hold indefinitely', isCorrect: false },
      { optionText: 'Transfer without explanation', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Company records should be kept:',
    options: [
      { optionText: 'Accurate and organized', isCorrect: true },
      { optionText: 'Hidden from review', isCorrect: false },
      { optionText: 'Edited freely without record', isCorrect: false },
      { optionText: 'Incomplete', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Login credentials for company systems should be:',
    options: [
      { optionText: 'Kept confidential and secure', isCorrect: true },
      { optionText: 'Shared with coworkers for convenience', isCorrect: false },
      { optionText: 'Posted publicly', isCorrect: false },
      { optionText: 'Written on a sticky note', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Scheduling conflicts for executives should be handled:',
    options: [
      { optionText: 'Randomly', isCorrect: false },
      { optionText: 'By ignoring one meeting', isCorrect: false },
      { optionText: 'Proactively and with clear communication', isCorrect: true },
      { optionText: 'Without informing anyone', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Sensitive company documents should be:',
    options: [
      { optionText: 'Left open on a shared screen', isCorrect: false },
      { optionText: 'Emailed to personal accounts', isCorrect: false },
      { optionText: 'Stored and shared according to confidentiality policy', isCorrect: true },
      { optionText: 'Discussed openly in public', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Expense reports should always be:',
    options: [
      { optionText: 'Estimated loosely', isCorrect: false },
      { optionText: 'Accurate and truthful', isCorrect: true },
      { optionText: 'Submitted late', isCorrect: false },
      { optionText: 'Inflated slightly', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Professional emails sent on behalf of an executive should be:',
    options: [
      { optionText: 'Sent without review', isCorrect: false },
      { optionText: 'Casual and unedited', isCorrect: false },
      { optionText: 'Clear, accurate, and proofread', isCorrect: true },
      { optionText: 'Written in slang', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'If you notice an error in a financial document, you should:',
    options: [
      { optionText: 'Wait for someone else to find it', isCorrect: false },
      { optionText: 'Hide it', isCorrect: false },
      { optionText: 'Leave it as is', isCorrect: false },
      { optionText: 'Correct it and report the issue', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You receive a request to share confidential meeting notes with someone outside the company. What should you do?',
    options: [
      { optionText: 'Share a summary instead', isCorrect: false },
      { optionText: 'Share them if asked nicely', isCorrect: false },
      { optionText: 'Forward them immediately', isCorrect: false },
      { optionText: 'Verify authorization before sharing any confidential information', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'An executive asks you to backdate a document. What should you do?',
    options: [
      { optionText: 'Decline and explain the ethical and legal concerns', isCorrect: true },
      { optionText: 'Comply without question', isCorrect: false },
      { optionText: 'Backdate it slightly', isCorrect: false },
      { optionText: 'Ignore the request silently', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You accidentally send a confidential email to the wrong recipient. What should you do?',
    options: [
      { optionText: 'Delete the evidence', isCorrect: false },
      { optionText: 'Wait and see if anyone notices', isCorrect: false },
      { optionText: 'Report it immediately and follow data incident procedures', isCorrect: true },
      { optionText: 'Say nothing', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Why is maintaining an accurate calendar important for an executive?',
    options: [
      { optionText: 'It is just a formality', isCorrect: false },
      { optionText: 'It has no real impact', isCorrect: false },
      { optionText: 'It prevents scheduling conflicts and missed commitments', isCorrect: true },
      { optionText: 'It only matters for external meetings', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A vendor offers you a personal gift in exchange for favorable contract terms. What should you do?',
    options: [
      { optionText: 'Decline and report the offer per company policy', isCorrect: true },
      { optionText: 'Accept it discreetly', isCorrect: false },
      { optionText: 'Accept only small gifts', isCorrect: false },
      { optionText: 'Negotiate a bigger gift', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'When taking minutes during a meeting, accuracy is important because:',
    options: [
      { optionText: 'Minutes are rarely reviewed', isCorrect: false },
      { optionText: 'They are only for personal use', isCorrect: false },
      { optionText: 'They serve as an official record of decisions made', isCorrect: true },
      { optionText: 'Accuracy does not matter much', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You are asked to file documents that appear to violate company policy. What should you do?',
    options: [
      { optionText: 'File them and tell no one', isCorrect: false },
      { optionText: 'Destroy the documents', isCorrect: false },
      { optionText: 'File them without question', isCorrect: false },
      { optionText: 'Raise the concern with the appropriate person before proceeding', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You discover an executive has been misreporting expenses. What should you do?',
    options: [
      { optionText: 'Report it through appropriate compliance channels', isCorrect: true },
      { optionText: 'Help cover it up', isCorrect: false },
      { optionText: 'Confront the executive publicly', isCorrect: false },
      { optionText: 'Ignore it since it is not your job', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'Two executives give you conflicting urgent instructions. What should you do?',
    options: [
      { optionText: 'Do neither task', isCorrect: false },
      { optionText: 'Pick the one you like better', isCorrect: false },
      { optionText: 'Ignore both', isCorrect: false },
      { optionText: 'Clarify priorities with both parties professionally', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You are asked to access a colleague\'s email without authorization. What should you do?',
    options: [
      { optionText: 'Do it only once', isCorrect: false },
      { optionText: 'Ask the colleague\'s permission afterward', isCorrect: false },
      { optionText: 'Do it quietly', isCorrect: false },
      { optionText: 'Refuse and report the request if appropriate', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A critical deadline conflicts with company data protection procedures. What should guide your decision?',
    options: [
      { optionText: 'Maintaining compliance even if it affects the timeline', isCorrect: true },
      { optionText: 'Skipping security steps to save time', isCorrect: false },
      { optionText: 'Meeting the deadline at all costs', isCorrect: false },
      { optionText: 'Letting someone else decide', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You notice unauthorized access attempts on a shared company system. What should you do?',
    options: [
      { optionText: 'Investigate it yourself secretly', isCorrect: false },
      { optionText: 'Report it immediately to IT or security', isCorrect: true },
      { optionText: 'Ignore it', isCorrect: false },
      { optionText: 'Change your own password only', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'Which best demonstrates strong administrative integrity?',
    options: [
      { optionText: 'Flagging an error in a contract before it is signed', isCorrect: true },
      { optionText: 'Approving documents without reading them', isCorrect: false },
      { optionText: 'Staying silent to avoid conflict', isCorrect: false },
      { optionText: 'Letting management catch errors themselves', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'An executive asks you to withhold information from auditors. What should you do?',
    options: [
      { optionText: 'Decline and escalate through proper compliance channels', isCorrect: true },
      { optionText: 'Withhold only minor details', isCorrect: false },
      { optionText: 'Ask the auditors to skip that section', isCorrect: false },
      { optionText: 'Comply since it is an instruction from leadership', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You are managing travel bookings and find a cheaper option that violates the travel policy. What should you do?',
    options: [
      { optionText: 'Book it anyway since it saves money', isCorrect: false },
      { optionText: 'Let the traveler decide unofficially', isCorrect: false },
      { optionText: 'Book it without telling anyone', isCorrect: false },
      { optionText: 'Follow the approved travel policy or seek an exception', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Maintaining version control on shared documents helps prevent:',
    options: [
      { optionText: 'Conflicting edits and lost information', isCorrect: true },
      { optionText: 'Larger file sizes', isCorrect: false },
      { optionText: 'Better formatting', isCorrect: false },
      { optionText: 'Faster completion only', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'If a guest arrives for a meeting the executive forgot about, you should:',
    options: [
      { optionText: 'Handle it courteously and find a workable solution', isCorrect: true },
      { optionText: 'Turn the guest away', isCorrect: false },
      { optionText: 'Argue with the guest', isCorrect: false },
      { optionText: 'Ignore the guest', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.ADMIN_EXECUTIVE,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You are asked to shred documents related to an ongoing investigation. What should you do?',
    options: [
      { optionText: 'Shred them and tell no one', isCorrect: false },
      { optionText: 'Shred only some of them', isCorrect: false },
      { optionText: 'Refuse and report the request immediately', isCorrect: true },
      { optionText: 'Shred them as instructed', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Personal protective equipment (PPE) in a warehouse should be:',
    options: [
      { optionText: 'Ignored if uncomfortable', isCorrect: false },
      { optionText: 'Worn as required', isCorrect: true },
      { optionText: 'Optional', isCorrect: false },
      { optionText: 'Used only by supervisors', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'When lifting heavy boxes, you should:',
    options: [
      { optionText: 'Twist while lifting', isCorrect: false },
      { optionText: 'Use proper lifting technique with your legs', isCorrect: true },
      { optionText: 'Bend your back and lift', isCorrect: false },
      { optionText: 'Lift as fast as possible', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Spilled liquids on the warehouse floor should be:',
    options: [
      { optionText: 'Left for someone else', isCorrect: false },
      { optionText: 'Stepped over carefully', isCorrect: false },
      { optionText: 'Ignored if small', isCorrect: false },
      { optionText: 'Cleaned up immediately and marked', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Stock counts should be recorded:',
    options: [
      { optionText: 'Accurately and promptly', isCorrect: true },
      { optionText: 'Approximately', isCorrect: false },
      { optionText: 'At the end of the month only', isCorrect: false },
      { optionText: 'From memory', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Aisles and walkways in a warehouse should be:',
    options: [
      { optionText: 'Kept clear of obstructions', isCorrect: true },
      { optionText: 'Blocked occasionally', isCorrect: false },
      { optionText: 'Narrowed for more storage', isCorrect: false },
      { optionText: 'Used for temporary storage', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Damaged or expired goods should be:',
    options: [
      { optionText: 'Identified, separated, and reported per procedure', isCorrect: true },
      { optionText: 'Ignored', isCorrect: false },
      { optionText: 'Mixed with good stock', isCorrect: false },
      { optionText: 'Sold at a discount without notice', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'FIFO (First In, First Out) is used to:',
    options: [
      { optionText: 'Randomize stock placement', isCorrect: false },
      { optionText: 'Slow down operations', isCorrect: false },
      { optionText: 'Rotate stock so older items are used first', isCorrect: true },
      { optionText: 'Use newest items first', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You notice a forklift operator not wearing a seatbelt. What should you do?',
    options: [
      { optionText: 'Report or remind them of the safety requirement', isCorrect: true },
      { optionText: 'Tell them after their shift ends', isCorrect: false },
      { optionText: 'Wait for an accident to happen', isCorrect: false },
      { optionText: 'Ignore it', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A stock count does not match the system records. What should you do?',
    options: [
      { optionText: 'Ignore the difference', isCorrect: false },
      { optionText: 'Adjust the system to match without investigation', isCorrect: false },
      { optionText: 'Guess which number is correct', isCorrect: false },
      { optionText: 'Investigate the discrepancy and report findings', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Hazardous materials in the warehouse should be:',
    options: [
      { optionText: 'Stored according to safety data sheets and labeling rules', isCorrect: true },
      { optionText: 'Stored with regular stock', isCorrect: false },
      { optionText: 'Stored anywhere convenient', isCorrect: false },
      { optionText: 'Left unlabeled', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You see a coworker stacking boxes above the recommended height limit. What should you do?',
    options: [
      { optionText: 'Take a photo for social media', isCorrect: false },
      { optionText: 'Point out the safety risk and correct it', isCorrect: true },
      { optionText: 'Help them stack higher', isCorrect: false },
      { optionText: 'Say nothing', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Why is accurate inventory labeling important?',
    options: [
      { optionText: 'It is only for appearance', isCorrect: false },
      { optionText: 'It prevents errors in order fulfillment and stock tracking', isCorrect: true },
      { optionText: 'It slows down operations', isCorrect: false },
      { optionText: 'It is not important', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A fire exit in the warehouse is partially blocked by pallets. What should you do?',
    options: [
      { optionText: 'Add a sign and leave it', isCorrect: false },
      { optionText: 'Move the pallets and report the issue', isCorrect: true },
      { optionText: 'Wait for the next inspection', isCorrect: false },
      { optionText: 'Leave it since it is mostly clear', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You suspect a coworker is stealing inventory. What should you do?',
    options: [
      { optionText: 'Confront them directly and aggressively', isCorrect: false },
      { optionText: 'Ignore it since it is not your responsibility', isCorrect: false },
      { optionText: 'Join in', isCorrect: false },
      { optionText: 'Report your concerns through proper channels', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You are behind on a shipment deadline and notice a shortcut that skips a required safety check. What should you do?',
    options: [
      { optionText: 'Skip the check to meet the deadline', isCorrect: false },
      { optionText: 'Complete the required safety check regardless of time pressure', isCorrect: true },
      { optionText: 'Skip it only this once', isCorrect: false },
      { optionText: 'Ask a coworker to skip it for you', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A shelving unit appears structurally unstable. What should you do?',
    options: [
      { optionText: 'Add more weight to test it', isCorrect: false },
      { optionText: 'Ignore it if it has not failed yet', isCorrect: false },
      { optionText: 'Report it and restrict access until inspected', isCorrect: true },
      { optionText: 'Keep using it carefully', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A large shipment arrives with visible chemical leakage. What should you prioritize?',
    options: [
      { optionText: 'Cleaning it without protective gear', isCorrect: false },
      { optionText: 'Hiding it from supervisors', isCorrect: false },
      { optionText: 'Following hazardous material containment and reporting procedures', isCorrect: true },
      { optionText: 'Unloading it quickly', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You are asked to falsify inventory records to hide a shortage. What should you do?',
    options: [
      { optionText: 'Falsify the records as instructed', isCorrect: false },
      { optionText: 'Refuse and report the request', isCorrect: true },
      { optionText: 'Quit without saying why', isCorrect: false },
      { optionText: 'Falsify only part of the records', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'During a power outage, automated inventory systems go offline. What should you do?',
    options: [
      { optionText: 'Continue working in the dark without caution', isCorrect: false },
      { optionText: 'Switch to manual tracking procedures and ensure safety', isCorrect: true },
      { optionText: 'Stop all operations and wait silently', isCorrect: false },
      { optionText: 'Estimate counts later from memory', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'Which action best demonstrates a strong inventory safety culture?',
    options: [
      { optionText: 'Only reporting actual injuries', isCorrect: false },
      { optionText: 'Avoiding paperwork for minor incidents', isCorrect: false },
      { optionText: 'Reporting near-misses even when no one was hurt', isCorrect: true },
      { optionText: 'Waiting for management to notice issues', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A supervisor pressures you to certify a stock count you have not verified. What should you do?',
    options: [
      { optionText: 'Decline until you can verify the count', isCorrect: true },
      { optionText: 'Certify only part of it', isCorrect: false },
      { optionText: 'Ask a coworker to certify it instead', isCorrect: false },
      { optionText: 'Certify it to avoid conflict', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Operating machinery you are not certified for is:',
    options: [
      { optionText: 'Acceptable if a supervisor is nearby', isCorrect: false },
      { optionText: 'Acceptable for short tasks', isCorrect: false },
      { optionText: 'Acceptable in emergencies only', isCorrect: false },
      { optionText: 'Not permitted under any circumstance', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Before operating a forklift, you should:',
    options: [
      { optionText: 'Perform a pre-operation safety inspection', isCorrect: true },
      { optionText: 'Start it without checking', isCorrect: false },
      { optionText: 'Skip the inspection if running late', isCorrect: false },
      { optionText: 'Ask someone else to inspect it later', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Loose or unsecured items on high shelves are:',
    options: [
      { optionText: 'Not a concern', isCorrect: false },
      { optionText: 'Fine if rarely accessed', isCorrect: false },
      { optionText: 'Someone else\'s responsibility', isCorrect: false },
      { optionText: 'A falling hazard that should be secured', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.INVENTORY,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You are asked to ship an order that fails a quality inspection. What should you do?',
    options: [
      { optionText: 'Ship it and apologize later if there is a problem', isCorrect: false },
      { optionText: 'Ship it since the customer is waiting', isCorrect: false },
      { optionText: 'Hold the shipment and report the failed inspection', isCorrect: true },
      { optionText: 'Ship part of it', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Standard operating procedures (SOPs) exist to:',
    options: [
      { optionText: 'Slow down work unnecessarily', isCorrect: false },
      { optionText: 'Apply only to new employees', isCorrect: false },
      { optionText: 'Ensure consistency and safety', isCorrect: true },
      { optionText: 'Be ignored when inconvenient', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Equipment malfunctions should be:',
    options: [
      { optionText: 'Ignored if minor', isCorrect: false },
      { optionText: 'Reported immediately', isCorrect: true },
      { optionText: 'Fixed without telling anyone', isCorrect: false },
      { optionText: 'Reported only at the end of the week', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Emergency exits and equipment should always be:',
    options: [
      { optionText: 'Accessible and unobstructed', isCorrect: true },
      { optionText: 'Locked during work hours', isCorrect: false },
      { optionText: 'Used for storage', isCorrect: false },
      { optionText: 'Blocked temporarily if needed', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Quality control checks during operations help to:',
    options: [
      { optionText: 'Add unnecessary paperwork', isCorrect: false },
      { optionText: 'Identify and correct issues early', isCorrect: true },
      { optionText: 'Replace the need for training', isCorrect: false },
      { optionText: 'Slow down production for no reason', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'If a process deviates from the documented procedure, you should:',
    options: [
      { optionText: 'Document and report the deviation', isCorrect: true },
      { optionText: 'Continue without telling anyone', isCorrect: false },
      { optionText: 'Change the procedure yourself', isCorrect: false },
      { optionText: 'Assume it is fine', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Workplace incidents, even minor ones, should be:',
    options: [
      { optionText: 'Kept private', isCorrect: false },
      { optionText: 'Forgotten quickly', isCorrect: false },
      { optionText: 'Discussed only informally', isCorrect: false },
      { optionText: 'Reported and documented', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Personal protective equipment compliance applies to:',
    options: [
      { optionText: 'No one if it is uncomfortable', isCorrect: false },
      { optionText: 'Visitors only', isCorrect: false },
      { optionText: 'Everyone in designated areas', isCorrect: true },
      { optionText: 'Only new staff', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A piece of equipment is making an unusual noise but still works. What should you do?',
    options: [
      { optionText: 'Continue using it until it fully fails', isCorrect: false },
      { optionText: 'Ignore the noise', isCorrect: false },
      { optionText: 'Report it for inspection before continuing use', isCorrect: true },
      { optionText: 'Use it only at night', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You are short-staffed and tempted to skip a safety briefing. What should you do?',
    options: [
      { optionText: 'Still conduct the safety briefing', isCorrect: true },
      { optionText: 'Have someone untrained run it', isCorrect: false },
      { optionText: 'Do a shorter version with no detail', isCorrect: false },
      { optionText: 'Skip it to save time', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A vendor delivers materials that do not meet quality specifications. What should you do?',
    options: [
      { optionText: 'Use them anyway to stay on schedule', isCorrect: false },
      { optionText: 'Use only the worst parts', isCorrect: false },
      { optionText: 'Reject them and follow the proper return process', isCorrect: true },
      { optionText: 'Mix them with good materials', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Why is cross-training important in operations?',
    options: [
      { optionText: 'It ensures continuity if staff are unavailable', isCorrect: true },
      { optionText: 'It only benefits management', isCorrect: false },
      { optionText: 'It slows down operations permanently', isCorrect: false },
      { optionText: 'It is not useful in practice', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You notice a coworker bypassing a safety lockout procedure on machinery. What should you do?',
    options: [
      { optionText: 'Say nothing since it is their choice', isCorrect: false },
      { optionText: 'Intervene and report the violation', isCorrect: true },
      { optionText: 'Help them bypass it faster', isCorrect: false },
      { optionText: 'Wait to see what happens', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A scheduled maintenance is delayed due to a busy production schedule. What should you do?',
    options: [
      { optionText: 'Reschedule it promptly without skipping it', isCorrect: true },
      { optionText: 'Let someone else worry about it', isCorrect: false },
      { optionText: 'Skip maintenance entirely', isCorrect: false },
      { optionText: 'Delay it indefinitely', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'When resources are limited, operational decisions should prioritize:',
    options: [
      { optionText: 'Cutting corners', isCorrect: false },
      { optionText: 'Personal convenience', isCorrect: false },
      { optionText: 'Safety and quality standards', isCorrect: true },
      { optionText: 'Speed above all else', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A production deadline is at risk unless a mandatory safety inspection is skipped. What should you do?',
    options: [
      { optionText: 'Skip it and inspect afterward', isCorrect: false },
      { optionText: 'Skip the inspection to meet the deadline', isCorrect: false },
      { optionText: 'Have an untrained worker do it quickly', isCorrect: false },
      { optionText: 'Complete the inspection and communicate any delay', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A critical machine fails during peak operations. What should you prioritize?',
    options: [
      { optionText: 'Hiding the failure from management', isCorrect: false },
      { optionText: 'Ignoring the failure until shift end', isCorrect: false },
      { optionText: 'Worker safety and proper shutdown procedure', isCorrect: true },
      { optionText: 'Forcing it to keep running', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You discover falsified quality control records from a previous shift. What should you do?',
    options: [
      { optionText: 'Confront the worker publicly', isCorrect: false },
      { optionText: 'Fix the records yourself quietly', isCorrect: false },
      { optionText: 'Report it through proper channels', isCorrect: true },
      { optionText: 'Ignore it since it was not your shift', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'During an emergency evacuation, what is the operations team\'s top priority?',
    options: [
      { optionText: 'Continuing production as long as possible', isCorrect: false },
      { optionText: 'Ensuring all personnel are safely accounted for', isCorrect: true },
      { optionText: 'Saving equipment first', isCorrect: false },
      { optionText: 'Documenting the event before evacuating', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A manager instructs you to operate beyond a safe capacity limit to meet targets. What should you do?',
    options: [
      { optionText: 'Comply since it is an instruction from leadership', isCorrect: false },
      { optionText: 'Raise the safety concern and decline if it remains unsafe', isCorrect: true },
      { optionText: 'Exceed the limit slightly', isCorrect: false },
      { optionText: 'Exceed it only when no one is watching', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'Which action best reflects a mature operations safety culture?',
    options: [
      { optionText: 'Discouraging staff from raising concerns', isCorrect: false },
      { optionText: 'Prioritizing output over hazard reporting', isCorrect: false },
      { optionText: 'Reporting near-miss incidents proactively', isCorrect: true },
      { optionText: 'Only documenting major accidents', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A new process increases efficiency but has not been safety-tested. What should you do?',
    options: [
      { optionText: 'Ensure proper safety testing and approval first', isCorrect: true },
      { optionText: 'Roll it out immediately company-wide', isCorrect: false },
      { optionText: 'Use it only when supervisors are absent', isCorrect: false },
      { optionText: 'Test it informally on one shift only', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Effective handover notes between shifts should be:',
    options: [
      { optionText: 'Brief and vague', isCorrect: false },
      { optionText: 'Verbal only with no documentation', isCorrect: false },
      { optionText: 'Skipped if the shift was uneventful', isCorrect: false },
      { optionText: 'Clear, complete, and accurate', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Unlabeled or unmarked hazardous areas should be:',
    options: [
      { optionText: 'Marked only if convenient', isCorrect: false },
      { optionText: 'Reported and properly marked', isCorrect: true },
      { optionText: 'Left as is', isCorrect: false },
      { optionText: 'Ignored by non-supervisors', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Daily equipment checklists exist to:',
    options: [
      { optionText: 'Add unnecessary work', isCorrect: false },
      { optionText: 'Catch problems before they cause incidents', isCorrect: true },
      { optionText: 'Replace the need for maintenance', isCorrect: false },
      { optionText: 'Be filled out only when convenient', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.OPERATIONS,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A new operations process conflicts with a long-standing informal workaround staff prefer. What should you do?',
    options: [
      { optionText: 'Allow both processes randomly', isCorrect: false },
      { optionText: 'Ignore the conflict', isCorrect: false },
      { optionText: 'Enforce the approved process and address concerns through proper channels', isCorrect: true },
      { optionText: 'Let staff keep using the informal workaround', isCorrect: false },
    ],
  },

  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Being punctual for work demonstrates:',
    options: [
      { optionText: 'Weakness', isCorrect: false },
      { optionText: 'Professionalism and reliability', isCorrect: true },
      { optionText: 'Carelessness', isCorrect: false },
      { optionText: 'Nothing significant', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'If you make a mistake at work, you should:',
    options: [
      { optionText: 'Blame a coworker', isCorrect: false },
      { optionText: 'Hide it', isCorrect: false },
      { optionText: 'Ignore it', isCorrect: false },
      { optionText: 'Take responsibility and correct it', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Respectful communication with colleagues means:',
    options: [
      { optionText: 'Interrupting often', isCorrect: false },
      { optionText: 'Listening and speaking courteously', isCorrect: true },
      { optionText: 'Ignoring others\' input', isCorrect: false },
      { optionText: 'Being condescending', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Workplace confidentiality means:',
    options: [
      { optionText: 'Sharing information only with close friends', isCorrect: false },
      { optionText: 'It does not matter', isCorrect: false },
      { optionText: 'Protecting sensitive information appropriately', isCorrect: true },
      { optionText: 'Discussing private matters openly', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'A positive attitude at work helps to:',
    options: [
      { optionText: 'Improve teamwork and morale', isCorrect: true },
      { optionText: 'Slow down productivity', isCorrect: false },
      { optionText: 'Have no real effect', isCorrect: false },
      { optionText: 'Cause unnecessary conflict', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Honesty in the workplace is:',
    options: [
      { optionText: 'Essential for trust and integrity', isCorrect: true },
      { optionText: 'Not very important', isCorrect: false },
      { optionText: 'Optional depending on the situation', isCorrect: false },
      { optionText: 'Only important for management', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Following company policies is important because they:',
    options: [
      { optionText: 'Only apply to certain people', isCorrect: false },
      { optionText: 'Help maintain consistency and fairness', isCorrect: true },
      { optionText: 'Are usually unnecessary', isCorrect: false },
      { optionText: 'Can be ignored if inconvenient', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'A coworker takes credit for your work in front of management. What should you do?',
    options: [
      { optionText: 'Spread rumors about them', isCorrect: false },
      { optionText: 'Address it calmly and professionally, in private if possible', isCorrect: true },
      { optionText: 'Confront them aggressively in public', isCorrect: false },
      { optionText: 'Say nothing and let it go', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You disagree with a decision made by your manager. What is the best approach?',
    options: [
      { optionText: 'Ignore the decision and do your own thing', isCorrect: false },
      { optionText: 'Raise your concerns respectfully through proper channels', isCorrect: true },
      { optionText: 'Refuse to work', isCorrect: false },
      { optionText: 'Complain to other coworkers', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You witness a coworker being disrespectful to another employee. What should you do?',
    options: [
      { optionText: 'Support the affected coworker and report the behavior', isCorrect: true },
      { optionText: 'Join in', isCorrect: false },
      { optionText: 'Laugh along', isCorrect: false },
      { optionText: 'Ignore it since it is not your business', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Receiving constructive criticism should be met with:',
    options: [
      { optionText: 'Resentment', isCorrect: false },
      { optionText: 'Denial', isCorrect: false },
      { optionText: 'Defensiveness', isCorrect: false },
      { optionText: 'Openness and a willingness to improve', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You are running late and will miss an important deadline. What should you do?',
    options: [
      { optionText: 'Make up an excuse afterward', isCorrect: false },
      { optionText: 'Blame circumstances without explanation', isCorrect: false },
      { optionText: 'Say nothing and submit it whenever', isCorrect: false },
      { optionText: 'Communicate proactively with your supervisor', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Working well in a diverse team requires:',
    options: [
      { optionText: 'Expecting everyone to think the same way', isCorrect: false },
      { optionText: 'Respecting different perspectives and backgrounds', isCorrect: true },
      { optionText: 'Avoiding people who are different', isCorrect: false },
      { optionText: 'Ignoring cultural differences', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'You overhear confidential company information by accident. What should you do?',
    options: [
      { optionText: 'Use it for personal benefit', isCorrect: false },
      { optionText: 'Post about it online', isCorrect: false },
      { optionText: 'Share it with friends', isCorrect: false },
      { optionText: 'Keep it confidential and not repeat it', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A coworker asks you to cover for them so they can leave early without approval. What should you do?',
    options: [
      { optionText: 'Politely decline and encourage them to get proper approval', isCorrect: true },
      { optionText: 'Report them immediately to everyone', isCorrect: false },
      { optionText: 'Agree to help them out', isCorrect: false },
      { optionText: 'Cover for them just this once', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You notice a pattern of unethical behavior by a senior staff member. What should you do?',
    options: [
      { optionText: 'Confront them publicly', isCorrect: false },
      { optionText: 'Report it through appropriate, confidential channels', isCorrect: true },
      { optionText: 'Stay silent out of fear', isCorrect: false },
      { optionText: 'Spread the information informally', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You are offered a personal benefit in exchange for bending a company rule. What should you do?',
    options: [
      { optionText: 'Negotiate a bigger benefit', isCorrect: false },
      { optionText: 'Accept if no one will find out', isCorrect: false },
      { optionText: 'Decline and report the offer if appropriate', isCorrect: true },
      { optionText: 'Accept only once', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A heavy personal workload is causing you to consider cutting corners on quality. What is the best approach?',
    options: [
      { optionText: 'Communicate the workload concern and maintain standards', isCorrect: true },
      { optionText: 'Cut corners quietly to keep up', isCorrect: false },
      { optionText: 'Ask a coworker to take credit for unfinished work', isCorrect: false },
      { optionText: 'Let quality slip without telling anyone', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'Which best demonstrates accountability in the workplace?',
    options: [
      { optionText: 'Downplaying the impact of an error', isCorrect: false },
      { optionText: 'Waiting to see if anyone notices a mistake', isCorrect: false },
      { optionText: 'Admitting an error before it is discovered by others', isCorrect: true },
      { optionText: 'Shifting blame to reduce personal risk', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'A team member is being excluded from group activities by others. What should you do?',
    options: [
      { optionText: 'Wait for management to notice', isCorrect: false },
      { optionText: 'Ignore it since it is a personal matter', isCorrect: false },
      { optionText: 'Join the exclusion to fit in', isCorrect: false },
      { optionText: 'Include them and address the behavior appropriately', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You receive credit for a project that was actually a team effort. What should you do?',
    options: [
      { optionText: 'Downplay the team\'s role further', isCorrect: false },
      { optionText: 'Acknowledge and credit your team\'s contributions', isCorrect: true },
      { optionText: 'Avoid mentioning the team at all', isCorrect: false },
      { optionText: 'Accept the credit silently', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.MEDIUM,
    weight: 5,
    question: 'Maintaining a professional appearance and conduct at work reflects:',
    options: [
      { optionText: 'Unnecessary effort', isCorrect: false },
      { optionText: 'Respect for the workplace and role', isCorrect: true },
      { optionText: 'Vanity', isCorrect: false },
      { optionText: 'Conformity for its own sake', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'Showing up prepared for meetings demonstrates:',
    options: [
      { optionText: 'Professionalism and respect for others\' time', isCorrect: true },
      { optionText: 'Unnecessary effort', isCorrect: false },
      { optionText: 'Nothing in particular', isCorrect: false },
      { optionText: 'Overconfidence', isCorrect: false },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.EASY,
    weight: 3,
    question: 'When you do not understand an instruction from a supervisor, you should:',
    options: [
      { optionText: 'Ignore the instruction', isCorrect: false },
      { optionText: 'Guess and proceed', isCorrect: false },
      { optionText: 'Ask a coworker instead of the supervisor', isCorrect: false },
      { optionText: 'Ask for clarification', isCorrect: true },
    ],
  },
  {
    category: QuestionCategory.SAFETY,
    jobRole: JobRole.GENERAL,
    difficulty: QuestionDifficulty.HARD,
    weight: 8,
    question: 'You learn that a close friend at work has been violating company policy. What should you do?',
    options: [
      { optionText: 'Ignore it since it is a personal relationship', isCorrect: false },
      { optionText: 'Handle it according to policy, setting personal feelings aside', isCorrect: true },
      { optionText: 'Warn them so they can hide it better', isCorrect: false },
      { optionText: 'Cover for them because they are your friend', isCorrect: false },
    ],
  },
];
